baseURL = "https://kingtuo123.com/"
title = "King's Blog"  # 网页标题
theme = "hugo-notes"

# 禁用标签分类/文章列表页等
disableKinds = ["taxonomy", "term", "section"]

[params]
	defaultTheme = "auto"       # 默认主题 light 或 dark 或 auto
	headerTitle = "夜不能寐"     # header 左上角标题

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
	[markup.tableOfContents]
		endLevel = 4
		ordered = false
		startLevel = 2
	[markup.highlight]
		noClasses = false
		guessSyntax = true
		codeFences = true

